import type { CatalogEntry } from "./types";

// Overzicht van alle app-connectors.
// Alleen namen en publieke informatie over de diensten; de implementaties zijn eigen
// definities in ./defs. Staat een id hieronder zonder definitie, dan is de status "gepland".
// [id, naam, categorie, beschrijving, website, heeft trigger]
type Row = [string, string, string, string, string?, boolean?];

const ROWS: Row[] = [
  ["action-network", "Action Network", "Marketing", "Activisten, events en petities beheren", "actionnetwork.org"],
  ["activecampaign", "ActiveCampaign", "Marketing", "E-mailmarketing en CRM: contacten, deals en lijsten", "activecampaign.com", true],
  ["acuity-scheduling", "Acuity Scheduling", "Productiviteit", "Afspraken plannen (trigger bij nieuwe afspraken)", "acuityscheduling.com", true],
  ["adalo", "Adalo", "Ontwikkeling", "No-code apps: collecties lezen en schrijven", "adalo.com"],
  ["affinity", "Affinity", "Verkoop & CRM", "Relatie-intelligentie: lijsten, personen en organisaties", "affinity.co", true],
  ["agile-crm", "Agile CRM", "Verkoop & CRM", "Contacten, bedrijven en deals", "agilecrm.com"],
  ["airtable", "Airtable", "Data & opslag", "Records in Airtable-bases lezen, maken, bijwerken en verwijderen", "airtable.com", true],
  ["airtop", "Airtop", "AI", "Cloud-browsers voor AI-agents", "airtop.ai"],
  ["amqp", "AMQP", "Ontwikkeling", "Berichten via AMQP 1.0 (bv. ActiveMQ, Azure Service Bus)", "amqp.org", true],
  ["apitemplate-io", "APITemplate.io", "Content & CMS", "Afbeeldingen en PDF's genereren uit templates", "apitemplate.io"],
  ["asana", "Asana", "Projectbeheer", "Taken, projecten en teams", "asana.com", true],
  ["autopilot", "Autopilot", "Marketing", "Marketingautomatisering: contacten en journeys", "autopilothq.com", true],
  ["aws-certificate-manager", "AWS Certificate Manager", "Cloud & infra", "SSL/TLS-certificaten beheren", "aws.amazon.com/certificate-manager"],
  ["aws-cognito", "AWS Cognito", "Beveiliging", "Gebruikers en groepen in user pools", "aws.amazon.com/cognito"],
  ["aws-comprehend", "AWS Comprehend", "AI", "Tekstanalyse: taal, sentiment en entiteiten", "aws.amazon.com/comprehend"],
  ["aws-dynamodb", "AWS DynamoDB", "Data & opslag", "Items in DynamoDB-tabellen", "aws.amazon.com/dynamodb"],
  ["aws-elb", "AWS Elastic Load Balancing", "Cloud & infra", "Load balancers en certificaten", "aws.amazon.com/elasticloadbalancing"],
  ["aws-iam", "AWS IAM", "Beveiliging", "Gebruikers, groepen en rollen", "aws.amazon.com/iam"],
  ["aws-lambda", "AWS Lambda", "Cloud & infra", "Lambda-functies aanroepen", "aws.amazon.com/lambda"],
  ["aws-rekognition", "AWS Rekognition", "AI", "Beeldanalyse", "aws.amazon.com/rekognition"],
  ["aws-s3", "AWS S3", "Bestanden", "Buckets en objecten in Amazon S3", "aws.amazon.com/s3"],
  ["aws-ses", "AWS SES", "Communicatie", "E-mail versturen via Amazon SES", "aws.amazon.com/ses"],
  ["aws-sns", "AWS SNS", "Communicatie", "Notificaties publiceren", "aws.amazon.com/sns", true],
  ["aws-sqs", "AWS SQS", "Ontwikkeling", "Berichten op Amazon SQS-queues", "aws.amazon.com/sqs"],
  ["aws-textract", "AWS Textract", "AI", "Tekst en tabellen uit documenten halen", "aws.amazon.com/textract"],
  ["aws-transcribe", "AWS Transcribe", "AI", "Spraak naar tekst", "aws.amazon.com/transcribe"],
  ["azure-cosmos-db", "Azure Cosmos DB", "Data & opslag", "Containers en items", "azure.microsoft.com/products/cosmos-db"],
  ["azure-storage", "Azure Storage", "Bestanden", "Blobs en containers", "azure.microsoft.com/products/storage"],
  ["bamboohr", "BambooHR", "HR", "Medewerkers, bestanden en rapporten", "bamboohr.com"],
  ["bannerbear", "Bannerbear", "Content & CMS", "Afbeeldingen genereren uit templates", "bannerbear.com"],
  ["baserow", "Baserow", "Data & opslag", "Rijen in Baserow-tabellen", "baserow.io"],
  ["beeminder", "Beeminder", "Productiviteit", "Doelen en datapunten", "beeminder.com"],
  ["bitbucket", "Bitbucket", "Ontwikkeling", "Repositories en events (trigger)", "bitbucket.org", true],
  ["bitly", "Bitly", "Marketing", "Links inkorten en beheren", "bitly.com"],
  ["bitwarden", "Bitwarden", "Beveiliging", "Collecties, groepen en leden", "bitwarden.com"],
  ["box", "Box", "Bestanden", "Bestanden en mappen", "box.com", true],
  ["brandfetch", "Brandfetch", "Marketing", "Logo's en merkgegevens ophalen", "brandfetch.com"],
  ["brevo", "Brevo", "Marketing", "E-mail/SMS-marketing en contacten (voorheen Sendinblue)", "brevo.com", true],
  ["bubble", "Bubble", "Ontwikkeling", "Objecten in Bubble-apps", "bubble.io"],
  ["cal-com", "Cal.com", "Productiviteit", "Boekingen (trigger)", "cal.com", true],
  ["calendly", "Calendly", "Productiviteit", "Geplande afspraken en webhooks", "calendly.com", true],
  ["chargebee", "Chargebee", "Financiën", "Abonnementen, klanten en facturen", "chargebee.com", true],
  ["circleci", "CircleCI", "Ontwikkeling", "Pipelines starten en volgen", "circleci.com"],
  ["cisco-webex", "Cisco Webex", "Communicatie", "Berichten en vergaderingen", "webex.com", true],
  ["clearbit", "Clearbit", "Verkoop & CRM", "Bedrijfs- en persoonsgegevens verrijken", "clearbit.com"],
  ["clickup", "ClickUp", "Projectbeheer", "Taken, lijsten en tijdregistratie", "clickup.com", true],
  ["clockify", "Clockify", "Productiviteit", "Tijdregistratie en projecten", "clockify.me", true],
  ["cloudflare", "Cloudflare", "Cloud & infra", "Zones en certificaten", "cloudflare.com"],
  ["cockpit", "Cockpit", "Content & CMS", "Collecties en singletons (headless CMS)", "getcockpit.com"],
  ["coda", "Coda", "Productiviteit", "Tabellen en formules in Coda-docs", "coda.io"],
  ["coingecko", "CoinGecko", "Financiën", "Cryptokoersen en marktdata", "coingecko.com"],
  ["contentful", "Contentful", "Content & CMS", "Entries en assets (headless CMS)", "contentful.com"],
  ["convertkit", "ConvertKit (Kit)", "Marketing", "Abonnees, formulieren en sequences", "kit.com", true],
  ["copper", "Copper", "Verkoop & CRM", "CRM voor Google Workspace", "copper.com", true],
  ["cortex", "Cortex", "Beveiliging", "Security-analyzers en responders", "thehive-project.org"],
  ["cratedb", "CrateDB", "Data & opslag", "SQL op CrateDB", "cratedb.com"],
  ["currents", "Currents", "Ontwikkeling", "Testresultaten (Playwright/Cypress)", "currents.dev"],
  ["customer-io", "Customer.io", "Marketing", "Klanten, events en campagnes", "customer.io", true],
  ["databricks", "Databricks", "Data & opslag", "SQL-warehouses en jobs", "databricks.com"],
  ["deepl", "DeepL", "AI", "Tekst vertalen", "deepl.com"],
  ["demio", "Demio", "Marketing", "Webinars en registraties", "demio.com"],
  ["dhl", "DHL", "E-commerce", "Zendingen volgen", "dhl.com"],
  ["discord", "Discord", "Communicatie", "Berichten versturen naar kanalen", "discord.com"],
  ["discourse", "Discourse", "Communicatie", "Forumposts, categorieën en gebruikers", "discourse.org"],
  ["disqus", "Disqus", "Social media", "Fora en reacties", "disqus.com"],
  ["drift", "Drift", "Klantenservice", "Contacten in Drift", "drift.com"],
  ["dropbox", "Dropbox", "Bestanden", "Bestanden en mappen", "dropbox.com"],
  ["dropcontact", "Dropcontact", "Verkoop & CRM", "Contactgegevens verrijken", "dropcontact.com"],
  ["egoi", "E-goi", "Marketing", "Contacten en lijsten", "e-goi.com"],
  ["elastic-security", "Elastic Security", "Beveiliging", "Cases en connectors", "elastic.co/security"],
  ["elasticsearch", "Elasticsearch", "Data & opslag", "Documenten en indexen", "elastic.co"],
  ["imap", "E-mail (IMAP)", "Communicatie", "Binnenkomende e-mail lezen (trigger)", "", true],
  ["emelia", "Emelia", "Marketing", "Cold-mailcampagnes", "emelia.io", true],
  ["erpnext", "ERPNext", "Financiën", "Documenten in ERPNext", "erpnext.com"],
  ["eventbrite", "Eventbrite", "Marketing", "Events en bestellingen (trigger)", "eventbrite.com", true],
  ["facebook-graph", "Facebook Graph API", "Social media", "Pagina's, posts en objecten via de Graph API", "developers.facebook.com", true],
  ["facebook-lead-ads", "Facebook Lead Ads", "Marketing", "Nieuwe leads (trigger)", "facebook.com/business", true],
  ["figma", "Figma", "Productiviteit", "Bestanden en reacties (trigger)", "figma.com", true],
  ["filemaker", "FileMaker", "Data & opslag", "Records in FileMaker-databases", "claris.com"],
  ["flow", "Flow", "Projectbeheer", "Taken in Flow — gepland: de API-documentatie van getflow.com is niet bereikbaar", "getflow.com", true],
  ["form-io", "Form.io", "Formulieren & enquêtes", "Formulierinzendingen (trigger)", "form.io", true],
  ["formstack", "Formstack", "Formulieren & enquêtes", "Formulierinzendingen (trigger)", "formstack.com", true],
  ["freshdesk", "Freshdesk", "Klantenservice", "Tickets en contacten", "freshdesk.com"],
  ["freshservice", "Freshservice", "Klantenservice", "IT-servicemanagement: tickets, assets en wijzigingen", "freshservice.com"],
  ["freshworks-crm", "Freshworks CRM", "Verkoop & CRM", "Contacten, accounts en deals", "freshworks.com/crm"],
  ["gsuite-admin", "Google Workspace Admin", "Beveiliging", "Gebruikers en groepen in Google Workspace", "workspace.google.com"],
  ["getresponse", "GetResponse", "Marketing", "Contacten en campagnes", "getresponse.com", true],
  ["ghost", "Ghost", "Content & CMS", "Posts op Ghost-blogs", "ghost.org"],
  ["github", "GitHub", "Ontwikkeling", "Issues, repositories, pull requests en releases", "github.com", true],
  ["gitlab", "GitLab", "Ontwikkeling", "Issues, projecten en releases", "gitlab.com", true],
  ["gmail", "Gmail", "Communicatie", "E-mail versturen, lezen en labelen", "gmail.com", true],
  ["gotowebinar", "GoTo Webinar", "Marketing", "Webinars en deelnemers", "goto.com/webinar"],
  ["gong", "Gong", "Verkoop & CRM", "Gesprekken en gebruikers", "gong.io"],
  ["google-ads", "Google Ads", "Marketing", "Campagnes en rapportages", "ads.google.com"],
  ["google-analytics", "Google Analytics", "Analyse", "Rapporten uit GA4", "analytics.google.com"],
  ["google-bigquery", "Google BigQuery", "Data & opslag", "Query's en records in BigQuery", "cloud.google.com/bigquery"],
  ["google-books", "Google Books", "Overig", "Boeken zoeken en boekenplanken", "books.google.com"],
  ["google-business-profile", "Google Business Profile", "Marketing", "Posts en reviews van je bedrijfsprofiel", "business.google.com", true],
  ["google-calendar", "Google Calendar", "Productiviteit", "Afspraken en agenda's", "calendar.google.com", true],
  ["google-chat", "Google Chat", "Communicatie", "Berichten in Chat-ruimtes", "chat.google.com"],
  ["google-cloud-natural-language", "Google Cloud Natural Language", "AI", "Sentiment en entiteiten", "cloud.google.com/natural-language"],
  ["google-cloud-storage", "Google Cloud Storage", "Bestanden", "Buckets en objecten", "cloud.google.com/storage"],
  ["google-contacts", "Google Contacts", "Verkoop & CRM", "Contactpersonen", "contacts.google.com"],
  ["google-docs", "Google Docs", "Productiviteit", "Documenten maken en bijwerken", "docs.google.com"],
  ["google-drive", "Google Drive", "Bestanden", "Bestanden en mappen", "drive.google.com", true],
  ["google-firestore", "Google Cloud Firestore", "Data & opslag", "Documenten en collecties", "firebase.google.com"],
  ["google-realtime-database", "Google Firebase Realtime Database", "Data & opslag", "Data lezen en schrijven", "firebase.google.com"],
  ["google-perspective", "Google Perspective", "AI", "Toxiciteit van tekst analyseren", "perspectiveapi.com"],
  ["google-sheets", "Google Sheets", "Data & opslag", "Rijen lezen, toevoegen, bijwerken en sheets beheren", "sheets.google.com", true],
  ["google-slides", "Google Slides", "Productiviteit", "Presentaties en pagina's", "slides.google.com"],
  ["google-tasks", "Google Tasks", "Productiviteit", "Taken en takenlijsten", "tasks.google.com"],
  ["google-translate", "Google Translate", "AI", "Tekst vertalen", "translate.google.com"],
  ["gotify", "Gotify", "Communicatie", "Pushberichten via Gotify", "gotify.net"],
  ["grafana", "Grafana", "Analyse", "Dashboards, teams en gebruikers", "grafana.com"],
  ["graphql", "GraphQL", "Ontwikkeling", "Willekeurige GraphQL-API aanroepen", "graphql.org"],
  ["grist", "Grist", "Data & opslag", "Records in Grist-documenten", "getgrist.com"],
  ["gumroad", "Gumroad", "E-commerce", "Verkopen en abonnementen (trigger)", "gumroad.com", true],
  ["hacker-news", "Hacker News", "Overig", "Artikelen en gebruikers", "news.ycombinator.com"],
  ["halopsa", "HaloPSA", "Klantenservice", "Tickets, klanten en sites", "halopsa.com"],
  ["harvest", "Harvest", "Productiviteit", "Tijdregistratie, projecten en facturen", "getharvest.com"],
  ["helpscout", "Help Scout", "Klantenservice", "Gesprekken en klanten", "helpscout.com", true],
  ["highlevel", "HighLevel", "Verkoop & CRM", "Contacten en kansen", "gohighlevel.com"],
  ["home-assistant", "Home Assistant", "Overig", "Apparaten en services in huis", "home-assistant.io"],
  ["hubspot", "HubSpot", "Verkoop & CRM", "Contacten, bedrijven, deals en tickets", "hubspot.com", true],
  ["humantic-ai", "Humantic AI", "AI", "Persoonlijkheidsprofielen", "humantic.ai"],
  ["hunter", "Hunter", "Verkoop & CRM", "E-mailadressen vinden en controleren", "hunter.io"],
  ["intercom", "Intercom", "Klantenservice", "Contacten, bedrijven en gesprekken", "intercom.com"],
  ["invoice-ninja", "Invoice Ninja", "Financiën", "Facturen, klanten en betalingen", "invoiceninja.com", true],
  ["iterable", "Iterable", "Marketing", "Gebruikers en events", "iterable.com"],
  ["jenkins", "Jenkins", "Ontwikkeling", "Jobs en builds", "jenkins.io"],
  ["jina-ai", "Jina AI", "AI", "Webpagina's lezen en zoeken voor AI", "jina.ai"],
  ["jira", "Jira Software", "Projectbeheer", "Issues, reacties en overgangen", "atlassian.com/software/jira", true],
  ["jotform", "Jotform", "Formulieren & enquêtes", "Formulierinzendingen (trigger)", "jotform.com", true],
  ["kafka", "Kafka", "Ontwikkeling", "Berichten op Kafka-topics", "kafka.apache.org", true],
  ["keap", "Keap", "Verkoop & CRM", "Contacten, bedrijven en bestellingen", "keap.com", true],
  ["kobotoolbox", "KoboToolbox", "Formulieren & enquêtes", "Formulieren en inzendingen", "kobotoolbox.org", true],
  ["ldap", "LDAP", "Beveiliging", "Gebruikers en groepen in een LDAP-directory", ""],
  ["lemlist", "lemlist", "Marketing", "Campagnes en leads", "lemlist.com", true],
  ["line", "Line", "Communicatie", "Notificaties via Line", "line.me"],
  ["linear", "Linear", "Projectbeheer", "Issues en projecten", "linear.app", true],
  ["lingvanex", "LingvaNex", "AI", "Tekst vertalen", "lingvanex.com"],
  ["linkedin", "LinkedIn", "Social media", "Posts plaatsen", "linkedin.com"],
  ["lonescale", "LoneScale", "Verkoop & CRM", "Lijsten en items", "lonescale.com", true],
  ["magento", "Magento 2", "E-commerce", "Producten, klanten en bestellingen", "magento.com"],
  ["mailcheck", "Mailcheck", "Marketing", "E-mailadressen valideren", "mailcheck.co"],
  ["mailchimp", "Mailchimp", "Marketing", "Lijsten, leden en campagnes", "mailchimp.com", true],
  ["mailerlite", "MailerLite", "Marketing", "Abonnees en groepen", "mailerlite.com", true],
  ["mailgun", "Mailgun", "Communicatie", "E-mail versturen", "mailgun.com"],
  ["mailjet", "Mailjet", "Communicatie", "E-mail en sms versturen", "mailjet.com", true],
  ["mandrill", "Mandrill", "Communicatie", "Transactionele e-mail", "mandrill.com"],
  ["marketstack", "Marketstack", "Financiën", "Beurskoersen", "marketstack.com"],
  ["matrix", "Matrix", "Communicatie", "Berichten en ruimtes", "matrix.org"],
  ["mattermost", "Mattermost", "Communicatie", "Berichten en kanalen", "mattermost.com"],
  ["mautic", "Mautic", "Marketing", "Contacten, bedrijven en segmenten", "mautic.org", true],
  ["medium", "Medium", "Content & CMS", "Posts publiceren", "medium.com"],
  ["messagebird", "MessageBird (Bird)", "Communicatie", "Sms versturen", "bird.com"],
  ["metabase", "Metabase", "Analyse", "Vragen, dashboards en databronnen", "metabase.com"],
  ["microsoft-dynamics-crm", "Microsoft Dynamics CRM", "Verkoop & CRM", "Accounts in Dynamics 365", "dynamics.microsoft.com"],
  ["microsoft-entra", "Microsoft Entra ID", "Beveiliging", "Gebruikers en groepen (Azure AD)", "entra.microsoft.com"],
  ["microsoft-excel", "Microsoft Excel 365", "Data & opslag", "Werkbladen, tabellen en bereiken", "microsoft.com/excel"],
  ["microsoft-graph-security", "Microsoft Graph Security", "Beveiliging", "Secure scores en meldingen", "learn.microsoft.com/graph/security"],
  ["microsoft-onedrive", "Microsoft OneDrive", "Bestanden", "Bestanden en mappen", "onedrive.com", true],
  ["microsoft-outlook", "Microsoft Outlook", "Communicatie", "E-mail, mappen en agenda", "outlook.com", true],
  ["microsoft-sharepoint", "Microsoft SharePoint", "Bestanden", "Lijsten, items en bestanden", "microsoft.com/sharepoint"],
  ["microsoft-sql", "Microsoft SQL Server", "Data & opslag", "SQL op Microsoft SQL Server", "microsoft.com/sql-server"],
  ["microsoft-teams", "Microsoft Teams", "Communicatie", "Berichten in kanalen en chats", "microsoft.com/teams", true],
  ["microsoft-todo", "Microsoft To Do", "Productiviteit", "Taken en lijsten", "todo.microsoft.com"],
  ["mindee", "Mindee", "AI", "Facturen en bonnen uitlezen", "mindee.com"],
  ["misp", "MISP", "Beveiliging", "Threat-intelligence: events en attributen", "misp-project.org"],
  ["mistral-ai", "Mistral AI", "AI", "Chat-completions en embeddings", "mistral.ai"],
  ["mocean", "Mocean", "Communicatie", "Sms en spraakberichten", "moceanapi.com"],
  ["monday", "monday.com", "Projectbeheer", "Borden, groepen en items", "monday.com"],
  ["mongodb", "MongoDB", "Data & opslag", "Documenten in MongoDB", "mongodb.com"],
  ["monica-crm", "Monica CRM", "Verkoop & CRM", "Persoonlijke CRM: contacten en activiteiten", "monicahq.com"],
  ["mqtt", "MQTT", "Ontwikkeling", "Berichten via MQTT", "mqtt.org", true],
  ["msg91", "MSG91", "Communicatie", "Sms versturen", "msg91.com"],
  ["mysql", "MySQL", "Data & opslag", "SQL op MySQL/MariaDB", "mysql.com"],
  ["nasa", "NASA", "Overig", "Open data van NASA (o.a. foto van de dag)", "api.nasa.gov"],
  ["netlify", "Netlify", "Cloud & infra", "Sites en deploys", "netlify.com", true],
  ["netscaler-adc", "Netscaler ADC", "Cloud & infra", "Certificaten en bestanden", "netscaler.com"],
  ["nextcloud", "Nextcloud", "Bestanden", "Bestanden, mappen en gebruikers", "nextcloud.com"],
  ["nocodb", "NocoDB", "Data & opslag", "Rijen in NocoDB-tabellen", "nocodb.com"],
  ["notion", "Notion", "Productiviteit", "Pagina's, databases en blokken", "notion.so", true],
  ["npm", "npm", "Ontwikkeling", "Pakketten en versies", "npmjs.com"],
  ["odoo", "Odoo", "Financiën", "Contacten, kansen en eigen modellen", "odoo.com"],
  ["okta", "Okta", "Beveiliging", "Gebruikers beheren", "okta.com"],
  ["one-simple-api", "One Simple API", "Overig", "Diverse hulp-API's (screenshots, pdf, …)", "onesimpleapi.com"],
  ["onfleet", "Onfleet", "E-commerce", "Bezorgtaken en koeriers", "onfleet.com", true],
  ["openai", "OpenAI", "AI", "Chat, embeddings en afbeeldingen", "openai.com"],
  ["openthesaurus", "OpenThesaurus", "Overig", "Synoniemen (Duits)", "openthesaurus.de"],
  ["openweathermap", "OpenWeatherMap", "Overig", "Actueel weer en voorspellingen", "openweathermap.org"],
  ["oracle-sql", "Oracle Database", "Data & opslag", "SQL op Oracle", "oracle.com/database"],
  ["orbit", "Orbit", "Marketing", "Community-leden en activiteiten — dienst gestopt in juli 2024 (overgenomen door Postman)", "orbit.love"],
  ["oura", "Oura", "Overig", "Slaap- en activiteitsdata", "ouraring.com"],
  ["paddle", "Paddle", "Financiën", "Klanten, abonnementen en betalingen", "paddle.com"],
  ["pagerduty", "PagerDuty", "Cloud & infra", "Incidenten en logboek", "pagerduty.com"],
  ["paypal", "PayPal", "Financiën", "Uitbetalingen en events", "paypal.com", true],
  ["peekalink", "Peekalink", "Overig", "Linkvoorbeelden ophalen", "peekalink.io"],
  ["perplexity", "Perplexity", "AI", "Vragen beantwoorden met bronnen", "perplexity.ai"],
  ["phantombuster", "Phantombuster", "Marketing", "Scraping-agents starten", "phantombuster.com"],
  ["philips-hue", "Philips Hue", "Overig", "Lampen aansturen", "philips-hue.com"],
  ["pipedrive", "Pipedrive", "Verkoop & CRM", "Deals, personen, organisaties en activiteiten", "pipedrive.com", true],
  ["plivo", "Plivo", "Communicatie", "Sms en gesprekken", "plivo.com"],
  ["posthog", "PostHog", "Analyse", "Events, aliassen en identiteiten", "posthog.com"],
  ["postmark", "Postmark", "Communicatie", "Transactionele e-mail (trigger)", "postmarkapp.com", true],
  ["profitwell", "ProfitWell", "Analyse", "Abonnementsmetrics", "profitwell.com"],
  ["pushbullet", "Pushbullet", "Communicatie", "Pushberichten", "pushbullet.com"],
  ["pushcut", "Pushcut", "Communicatie", "iOS-notificaties", "pushcut.io", true],
  ["pushover", "Pushover", "Communicatie", "Pushberichten naar telefoon", "pushover.net"],
  ["questdb", "QuestDB", "Data & opslag", "Tijdreeksdatabase", "questdb.io"],
  ["quickbase", "Quickbase", "Data & opslag", "Records en velden", "quickbase.com"],
  ["quickbooks", "QuickBooks Online", "Financiën", "Klanten, facturen en betalingen", "quickbooks.intuit.com"],
  ["quickchart", "QuickChart", "Analyse", "Grafieken als afbeelding", "quickchart.io"],
  ["rabbitmq", "RabbitMQ", "Ontwikkeling", "Berichten op RabbitMQ-queues", "rabbitmq.com", true],
  ["raindrop", "Raindrop", "Productiviteit", "Bladwijzers en collecties", "raindrop.io"],
  ["reddit", "Reddit", "Social media", "Posts en reacties", "reddit.com"],
  ["redis", "Redis", "Data & opslag", "Sleutels en waarden", "redis.io", true],
  ["rocketchat", "Rocket.Chat", "Communicatie", "Berichten in kanalen", "rocket.chat"],
  ["rss", "RSS-feed", "Content & CMS", "RSS-feeds lezen (trigger bij nieuwe items)", "", true],
  ["rundeck", "Rundeck", "Cloud & infra", "Jobs uitvoeren", "rundeck.com"],
  ["salesforce", "Salesforce", "Verkoop & CRM", "Leads, contacten, accounts, kansen en SOQL", "salesforce.com", true],
  ["salesmate", "Salesmate", "Verkoop & CRM", "Contacten, bedrijven en deals", "salesmate.io"],
  ["seatable", "SeaTable", "Data & opslag", "Rijen in SeaTable-bases", "seatable.io", true],
  ["securityscorecard", "SecurityScorecard", "Beveiliging", "Scores en rapportages", "securityscorecard.com"],
  ["segment", "Segment", "Analyse", "Events, identify en track", "segment.com"],
  ["sendgrid", "SendGrid", "Communicatie", "E-mail versturen en contacten", "sendgrid.com"],
  ["sendy", "Sendy", "Marketing", "Campagnes en abonnees", "sendy.co"],
  ["sentry-io", "Sentry.io", "Ontwikkeling", "Issues, events en releases", "sentry.io"],
  ["servicenow", "ServiceNow", "Klantenservice", "Incidenten, gebruikers en tabellen", "servicenow.com"],
  ["shopify", "Shopify", "E-commerce", "Producten, bestellingen en klanten", "shopify.com", true],
  ["signl4", "SIGNL4", "Cloud & infra", "Alarmen naar teams", "signl4.com"],
  ["slack", "Slack", "Communicatie", "Berichten, kanalen en gebruikers", "slack.com", true],
  ["seven", "seven (sms77)", "Communicatie", "Sms en spraakberichten", "seven.io"],
  ["snowflake", "Snowflake", "Data & opslag", "SQL op Snowflake", "snowflake.com"],
  ["splunk", "Splunk", "Beveiliging", "Zoekopdrachten en meldingen", "splunk.com"],
  ["spotify", "Spotify", "Overig", "Afspeellijsten en nummers", "spotify.com"],
  ["ssh", "SSH", "Cloud & infra", "Commando's uitvoeren op een server", ""],
  ["stackby", "Stackby", "Data & opslag", "Rijen in Stackby-tabellen", "stackby.com"],
  ["storyblok", "Storyblok", "Content & CMS", "Stories (headless CMS)", "storyblok.com"],
  ["strapi", "Strapi", "Content & CMS", "Entries (headless CMS)", "strapi.io"],
  ["strava", "Strava", "Overig", "Activiteiten (trigger)", "strava.com", true],
  ["stripe", "Stripe", "Financiën", "Klanten, betalingen, facturen en events", "stripe.com", true],
  ["supabase", "Supabase", "Data & opslag", "Rijen in Supabase (Postgres) via de REST-API", "supabase.com"],
  ["surveymonkey", "SurveyMonkey", "Formulieren & enquêtes", "Antwoorden (trigger)", "surveymonkey.com", true],
  ["syncromsp", "SyncroMSP", "Klantenservice", "Klanten, tickets en contacten", "syncromsp.com"],
  ["taiga", "Taiga", "Projectbeheer", "Issues en user stories", "taiga.io", true],
  ["tapfiliate", "Tapfiliate", "Marketing", "Affiliates en programma's", "tapfiliate.com"],
  ["telegram", "Telegram", "Communicatie", "Berichten en bestanden via een bot", "telegram.org", true],
  ["thehive", "TheHive", "Beveiliging", "Cases, alerts en observables", "thehive-project.org", true],
  ["timescaledb", "TimescaleDB", "Data & opslag", "Tijdreeksen in Postgres", "timescale.com"],
  ["todoist", "Todoist", "Productiviteit", "Taken en projecten", "todoist.com"],
  ["toggl", "Toggl Track", "Productiviteit", "Tijdregistratie (trigger)", "toggl.com", true],
  ["travis-ci", "Travis CI", "Ontwikkeling", "Builds", "travis-ci.com"],
  ["trello", "Trello", "Projectbeheer", "Borden, lijsten en kaarten", "trello.com", true],
  ["twake", "Twake", "Communicatie", "Berichten", "twake.app"],
  ["twilio", "Twilio", "Communicatie", "Sms, WhatsApp en gesprekken", "twilio.com", true],
  ["twist", "Twist", "Communicatie", "Kanalen en berichten", "twist.com"],
  ["x-twitter", "X (Twitter)", "Social media", "Posts plaatsen, zoeken en verwijderen", "x.com"],
  ["typeform", "Typeform", "Formulieren & enquêtes", "Formulieren en antwoorden", "typeform.com", true],
  ["uproc", "uProc", "Overig", "Data verrijken en valideren", "uproc.io"],
  ["unleashed-software", "Unleashed Software", "E-commerce", "Voorraad en verkooporders", "unleashedsoftware.com"],
  ["uplead", "UpLead", "Verkoop & CRM", "Bedrijfs- en persoonsgegevens verrijken", "uplead.com"],
  ["uptimerobot", "UptimeRobot", "Cloud & infra", "Monitors en statuspagina's", "uptimerobot.com"],
  ["urlscan-io", "urlscan.io", "Beveiliging", "URL's scannen", "urlscan.io"],
  ["venafi-cloud", "Venafi TLS Protect Cloud", "Beveiliging", "Certificaten beheren", "venafi.com"],
  ["venafi-datacenter", "Venafi TLS Protect Datacenter", "Beveiliging", "Certificaten beheren", "venafi.com"],
  ["vero", "Vero", "Marketing", "Gebruikers en events", "getvero.com"],
  ["vonage", "Vonage", "Communicatie", "Sms versturen", "vonage.com"],
  ["webflow", "Webflow", "Content & CMS", "CMS-items (trigger)", "webflow.com", true],
  ["wekan", "Wekan", "Projectbeheer", "Borden, lijsten en kaarten", "wekan.github.io"],
  ["whatsapp", "WhatsApp Business", "Communicatie", "Berichten via de WhatsApp Cloud API", "business.whatsapp.com", true],
  ["wise", "Wise", "Financiën", "Rekeningen, wisselkoersen en overboekingen", "wise.com", true],
  ["woocommerce", "WooCommerce", "E-commerce", "Producten, bestellingen en klanten", "woocommerce.com", true],
  ["wordpress", "WordPress", "Content & CMS", "Posts, pagina's en gebruikers", "wordpress.org"],
  ["workable", "Workable", "HR", "Kandidaten en vacatures (trigger)", "workable.com", true],
  ["wufoo", "Wufoo", "Formulieren & enquêtes", "Formulierinzendingen (trigger)", "wufoo.com", true],
  ["xero", "Xero", "Financiën", "Contacten en facturen", "xero.com"],
  ["youtube", "YouTube", "Social media", "Kanalen, video's en afspeellijsten", "youtube.com"],
  ["yourls", "Yourls", "Marketing", "Links inkorten", "yourls.org"],
  ["zammad", "Zammad", "Klantenservice", "Tickets, gebruikers en organisaties", "zammad.org"],
  ["zendesk", "Zendesk", "Klantenservice", "Tickets, gebruikers en organisaties", "zendesk.com", true],
  ["zoho-crm", "Zoho CRM", "Verkoop & CRM", "Leads, contacten, accounts en deals", "zoho.com/crm"],
  ["zoom", "Zoom", "Communicatie", "Vergaderingen plannen en beheren", "zoom.us"],
  ["zulip", "Zulip", "Communicatie", "Berichten en streams", "zulip.com"]
];

export const CATALOG: CatalogEntry[] = ROWS.map(([id, name, category, description, website, hasTrigger]) => ({
  id, name, category, description, ...(website ? { website: `https://${website}` } : {}), ...(hasTrigger ? { hasTrigger: true } : {})
}));

export const CATEGORIES = [...new Set(ROWS.map((r) => r[2]))].sort((a, b) => a.localeCompare(b, "nl"));
